apiVersion: apps/v1
kind: Deployment
metadata:
  name: exbert
  namespace: visdemos
spec:
  replicas: 1
  selector:
    matchLabels:
      run: exbert
  strategy:
    type: Recreate
  template:
    metadata:
      name: exbert
      namespace: visdemos
      labels:
        run: exbert
    spec:
      containers:
        - name: exbert
          image: us.icr.io/research3/visdemos/hoo/exbert:v0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          volumeMounts:
            - mountPath: "/app/server/data"
              name: cos-data
          resources:
            requests:
              cpu: 8
              memory: 30G
              nvidia.com/gpu: 0
            limits:
              cpu: 8
              memory: 30G
              nvidia.com/gpu: 0
          env:
            - name: PYTORCH_PRETRAINED_BERT_CACHE
              value: /app/server/data/models/
      imagePullSecrets:
        - name: all-icr-io
      volumes:
        - name: cos-data
          persistentVolumeClaim:
            claimName: cos-exbert-osc
